version: 2
updates:
  - package-ecosystem: "composer"
    directories:
      - "/**"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/**"
    schedule:
      interval: "weekly"
