name: Create Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip each folder
        run: |
          for d in */ ; do
            zip -r "${d%/}.zip" "$d"
          done

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - name: Release
        uses: MarvinPinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}"
          prerelease: false
          files: "*.zip"
